# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios, ‘7.0’
use_frameworks!

target 'PaymentezSDKSample' do
  pod 'AFNetworking'
  pod ‘CardIO’
end

target 'PaymentezSDKSampleTests' do

end

target 'PaymentezSDKSampleUITests' do

end

